import React from 'react'
import Hero from '../components/hero'
import { Metadata } from 'next'

export const metadata:Metadata = {
  title: 'Happy Chinese New Year Eve',
  description: 'Generated by create next app',
}

export default function page() {
  return (
    <Hero 
      image="/R0002997.jpg"
      title="新年快乐，蛇年大吉"
    />
  )
}
